### ISSUE TITLE
Miprem requires authentication

### ISSUE THREAD

**Issue by domi41** [MieuxVoter/mv-api-server-apiplatform#8]
```
  - Installing ramsey/uuid-doctrine (1.5.0): Loading from cache
  - Installing zordius/lightncandy (v1.2.5): Loading from cache
  - Installing roipoussiere/miprem-php (dev-master ce1c889):     Authentication required (framagit.org):
      Username: 
      Password:
```

@roipoussiere ?  Is the repo private ?

**Comment by roipoussiere** [comment]
Very strange because miprem-php and miprem sources are available publicly:

- https://framagit.org/roipoussiere/miprem-php
- https://framagit.org/roipoussiere/miprem

**Comment by domi41** [comment]
I'm not sure…
I have a pretty convoluted SSH setup on my machines, perhaps it's what's causing this ?

Could you try cloning this project and running `composer install`, see if it happens to you ?

**Comment by roipoussiere** [comment]
No problem to do this without authentication:

![image](https://user-images.githubusercontent.com/1665542/109726743-85422880-7bb3-11eb-9cf8-1efa843f0678.png)

**Comment by domi41** [comment]
Thanks !

It's probably a local issue then ; I'll re-open if it arises again.
